name: gemini_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  get_it: ^7.6.7
  connectivity_plus: ^5.0.2
  intl: ^0.19.0
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  path_provider: ^2.1.2
  permission_handler: ^11.2.0
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  flutter_switch: ^0.3.2
  flutter_screenutil: ^5.9.0
  shimmer: ^3.0.0
  injectable: ^1.5.3
  cupertino_icons: ^1.0.6
  smooth_page_indicator: ^1.1.0
  lottie: ^3.0.0
  flutter_native_splash: ^2.3.10
  objectbox_flutter_libs: ^2.5.0
  objectbox: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator: ^1.5.4
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.13.1
  objectbox_generator: ^2.5.0

flutter:
  uses-material-design: true
